// auto-generated file
export var LinkQualification;
(function (LinkQualification) {
    LinkQualification["Exact"] = "Exact";
    LinkQualification["Narrower"] = "Narrower";
    LinkQualification["Broader"] = "Broader";
    LinkQualification["Approximate"] = "Approximate";
    LinkQualification["Sequence"] = "Sequence";
    LinkQualification["Parent"] = "Parent";
    LinkQualification["Child"] = "Child";
    LinkQualification["RelatedCode"] = "RelatedCode";
    LinkQualification["LinkedPackage"] = "LinkedPackage";
    LinkQualification["RelatedService"] = "RelatedService";
    LinkQualification["InResponseTo"] = "InResponseTo";
    LinkQualification["Replaces"] = "Replaces";
    LinkQualification["Transforms"] = "Transforms";
    LinkQualification["TransformsAndReplaces"] = "TransformsAndReplaces";
    LinkQualification["AppendsTo"] = "AppendsTo";
    LinkQualification["BasedOn"] = "BasedOn";
    LinkQualification["DerivedFrom"] = "DerivedFrom";
    LinkQualification["Device"] = "Device";
    LinkQualification["Focus"] = "Focus";
    LinkQualification["HasMember"] = "HasMember";
    LinkQualification["Performer"] = "Performer";
    LinkQualification["Specimen"] = "Specimen";
    LinkQualification["ResultInterpreter"] = "ResultInterpreter";
    LinkQualification["Request"] = "Request";
})(LinkQualification || (LinkQualification = {}));
//# sourceMappingURL=LinkQualification.mjs.map