import { CodeStub } from './base/CodeStub.mjs';
import { HasEncryptionMetadata } from './base/HasEncryptionMetadata.mjs';
import { ICureDocument } from './base/ICureDocument.mjs';
import { StoredDocument } from './base/StoredDocument.mjs';
import { Address, DecryptedAddress, EncryptedAddress } from './embed/Address.mjs';
import { CalendarItemTag, DecryptedCalendarItemTag, EncryptedCalendarItemTag } from './embed/CalendarItemTag.mjs';
import { Delegation } from './embed/Delegation.mjs';
import { Encryptable } from './embed/Encryptable.mjs';
import { FlowItem } from './embed/FlowItem.mjs';
import { SecurityMetadata } from './embed/SecurityMetadata.mjs';
import { Base64String } from './specializations/Base64String.mjs';
export interface CalendarItem extends StoredDocument, ICureDocument<string>, HasEncryptionMetadata, Encryptable {
    title: string | undefined;
    calendarItemTypeId: string | undefined;
    masterCalendarItemId: string | undefined;
    patientId: string | undefined;
    important: boolean | undefined;
    homeVisit: boolean | undefined;
    phoneNumber: string | undefined;
    placeId: string | undefined;
    address: Address | undefined;
    addressText: string | undefined;
    startTime: number | undefined;
    endTime: number | undefined;
    confirmationTime: number | undefined;
    cancellationTimestamp: number | undefined;
    confirmationId: string | undefined;
    duration: number | undefined;
    allDay: boolean | undefined;
    details: string | undefined;
    wasMigrated: boolean | undefined;
    agendaId: string | undefined;
    hcpId: string | undefined;
    recurrenceId: string | undefined;
    meetingTags: Array<CalendarItemTag>;
    flowItem: FlowItem | undefined;
    readonly isEncrypted: boolean;
}
export declare class DecryptedCalendarItem {
    id: string;
    rev: string | undefined;
    created: number | undefined;
    modified: number | undefined;
    author: string | undefined;
    responsible: string | undefined;
    medicalLocationId: string | undefined;
    tags: Array<CodeStub>;
    codes: Array<CodeStub>;
    endOfLife: number | undefined;
    deletionDate: number | undefined;
    title: string | undefined;
    calendarItemTypeId: string | undefined;
    masterCalendarItemId: string | undefined;
    patientId: string | undefined;
    important: boolean | undefined;
    homeVisit: boolean | undefined;
    phoneNumber: string | undefined;
    placeId: string | undefined;
    address: DecryptedAddress | undefined;
    addressText: string | undefined;
    startTime: number | undefined;
    endTime: number | undefined;
    confirmationTime: number | undefined;
    cancellationTimestamp: number | undefined;
    confirmationId: string | undefined;
    duration: number | undefined;
    allDay: boolean | undefined;
    details: string | undefined;
    wasMigrated: boolean | undefined;
    agendaId: string | undefined;
    hcpId: string | undefined;
    recurrenceId: string | undefined;
    meetingTags: Array<DecryptedCalendarItemTag>;
    flowItem: FlowItem | undefined;
    secretForeignKeys: Array<string>;
    cryptedForeignKeys: {
        [key: string]: Array<Delegation>;
    };
    delegations: {
        [key: string]: Array<Delegation>;
    };
    encryptionKeys: {
        [key: string]: Array<Delegation>;
    };
    encryptedSelf: Base64String | undefined;
    securityMetadata: SecurityMetadata | undefined;
    readonly isEncrypted: false;
    constructor(partial: Partial<DecryptedCalendarItem>);
}
export declare class EncryptedCalendarItem {
    id: string;
    rev: string | undefined;
    created: number | undefined;
    modified: number | undefined;
    author: string | undefined;
    responsible: string | undefined;
    medicalLocationId: string | undefined;
    tags: Array<CodeStub>;
    codes: Array<CodeStub>;
    endOfLife: number | undefined;
    deletionDate: number | undefined;
    title: string | undefined;
    calendarItemTypeId: string | undefined;
    masterCalendarItemId: string | undefined;
    patientId: string | undefined;
    important: boolean | undefined;
    homeVisit: boolean | undefined;
    phoneNumber: string | undefined;
    placeId: string | undefined;
    address: EncryptedAddress | undefined;
    addressText: string | undefined;
    startTime: number | undefined;
    endTime: number | undefined;
    confirmationTime: number | undefined;
    cancellationTimestamp: number | undefined;
    confirmationId: string | undefined;
    duration: number | undefined;
    allDay: boolean | undefined;
    details: string | undefined;
    wasMigrated: boolean | undefined;
    agendaId: string | undefined;
    hcpId: string | undefined;
    recurrenceId: string | undefined;
    meetingTags: Array<EncryptedCalendarItemTag>;
    flowItem: FlowItem | undefined;
    secretForeignKeys: Array<string>;
    cryptedForeignKeys: {
        [key: string]: Array<Delegation>;
    };
    delegations: {
        [key: string]: Array<Delegation>;
    };
    encryptionKeys: {
        [key: string]: Array<Delegation>;
    };
    encryptedSelf: Base64String | undefined;
    securityMetadata: SecurityMetadata | undefined;
    readonly isEncrypted: true;
    constructor(partial: Partial<EncryptedCalendarItem>);
}
