import { CodeStub } from './base/CodeStub.mjs';
import { ICureDocument } from './base/ICureDocument.mjs';
import { ReportVersion } from './base/ReportVersion.mjs';
import { StoredDocument } from './base/StoredDocument.mjs';
import { DocumentGroup } from './embed/DocumentGroup.mjs';
import { DocumentType } from './embed/DocumentType.mjs';
export declare class DocumentTemplate implements StoredDocument, ICureDocument<string> {
    id: string;
    rev: string | undefined;
    created: number | undefined;
    modified: number | undefined;
    author: string | undefined;
    responsible: string | undefined;
    medicalLocationId: string | undefined;
    tags: Array<CodeStub>;
    codes: Array<CodeStub>;
    endOfLife: number | undefined;
    deletionDate: number | undefined;
    attachment: Int8Array | undefined;
    documentType: DocumentType | undefined;
    mainUti: string | undefined;
    name: string | undefined;
    otherUtis: Array<string>;
    attachmentId: string | undefined;
    version: ReportVersion | undefined;
    owner: string | undefined;
    guid: string | undefined;
    group: DocumentGroup | undefined;
    descr: string | undefined;
    disabled: string | undefined;
    specialty: CodeStub | undefined;
    constructor(partial: Partial<DocumentTemplate>);
}
