import { CodeStub } from './base/CodeStub.mjs';
import { HasEncryptionMetadata } from './base/HasEncryptionMetadata.mjs';
import { ICureDocument } from './base/ICureDocument.mjs';
import { StoredDocument } from './base/StoredDocument.mjs';
import { Delegation } from './embed/Delegation.mjs';
import { Encryptable } from './embed/Encryptable.mjs';
import { IdentityDocumentReader } from './embed/IdentityDocumentReader.mjs';
import { InvoiceInterventionType } from './embed/InvoiceInterventionType.mjs';
import { InvoiceType } from './embed/InvoiceType.mjs';
import { DecryptedInvoicingCode, EncryptedInvoicingCode, InvoicingCode } from './embed/InvoicingCode.mjs';
import { MediumType } from './embed/MediumType.mjs';
import { Payment } from './embed/Payment.mjs';
import { PaymentType } from './embed/PaymentType.mjs';
import { SecurityMetadata } from './embed/SecurityMetadata.mjs';
import { Base64String } from './specializations/Base64String.mjs';
export interface Invoice extends StoredDocument, ICureDocument<string>, HasEncryptionMetadata, Encryptable {
    invoiceDate: number | undefined;
    sentDate: number | undefined;
    printedDate: number | undefined;
    invoicingCodes: Array<InvoicingCode>;
    receipts: {
        [key: string]: string;
    };
    recipientType: string | undefined;
    recipientId: string | undefined;
    invoiceReference: string | undefined;
    thirdPartyReference: string | undefined;
    thirdPartyPaymentJustification: string | undefined;
    thirdPartyPaymentReason: string | undefined;
    reason: string | undefined;
    invoiceType: InvoiceType | undefined;
    sentMediumType: MediumType | undefined;
    interventionType: InvoiceInterventionType | undefined;
    groupId: string | undefined;
    paymentType: PaymentType | undefined;
    paid: number | undefined;
    payments: Array<Payment> | undefined;
    gnotionNihii: string | undefined;
    gnotionSsin: string | undefined;
    gnotionLastName: string | undefined;
    gnotionFirstName: string | undefined;
    gnotionCdHcParty: string | undefined;
    invoicePeriod: number | undefined;
    careProviderType: string | undefined;
    internshipNihii: string | undefined;
    internshipSsin: string | undefined;
    internshipLastName: string | undefined;
    internshipFirstName: string | undefined;
    internshipCdHcParty: string | undefined;
    internshipCbe: string | undefined;
    supervisorNihii: string | undefined;
    supervisorSsin: string | undefined;
    supervisorLastName: string | undefined;
    supervisorFirstName: string | undefined;
    supervisorCdHcParty: string | undefined;
    supervisorCbe: string | undefined;
    error: string | undefined;
    encounterLocationName: string | undefined;
    encounterLocationNihii: string | undefined;
    encounterLocationNorm: number | undefined;
    longDelayJustification: number | undefined;
    correctiveInvoiceId: string | undefined;
    correctedInvoiceId: string | undefined;
    creditNote: boolean | undefined;
    creditNoteRelatedInvoiceId: string | undefined;
    idDocument: IdentityDocumentReader | undefined;
    admissionDate: number | undefined;
    locationNihii: string | undefined;
    locationService: number | undefined;
    cancelReason: string | undefined;
    cancelDate: number | undefined;
    options: {
        [key: string]: string;
    };
    readonly isEncrypted: boolean;
}
export declare class DecryptedInvoice {
    id: string;
    rev: string | undefined;
    created: number | undefined;
    modified: number | undefined;
    author: string | undefined;
    responsible: string | undefined;
    medicalLocationId: string | undefined;
    tags: Array<CodeStub>;
    codes: Array<CodeStub>;
    endOfLife: number | undefined;
    deletionDate: number | undefined;
    invoiceDate: number | undefined;
    sentDate: number | undefined;
    printedDate: number | undefined;
    invoicingCodes: Array<DecryptedInvoicingCode>;
    receipts: {
        [key: string]: string;
    };
    recipientType: string | undefined;
    recipientId: string | undefined;
    invoiceReference: string | undefined;
    thirdPartyReference: string | undefined;
    thirdPartyPaymentJustification: string | undefined;
    thirdPartyPaymentReason: string | undefined;
    reason: string | undefined;
    invoiceType: InvoiceType | undefined;
    sentMediumType: MediumType | undefined;
    interventionType: InvoiceInterventionType | undefined;
    groupId: string | undefined;
    paymentType: PaymentType | undefined;
    paid: number | undefined;
    payments: Array<Payment> | undefined;
    gnotionNihii: string | undefined;
    gnotionSsin: string | undefined;
    gnotionLastName: string | undefined;
    gnotionFirstName: string | undefined;
    gnotionCdHcParty: string | undefined;
    invoicePeriod: number | undefined;
    careProviderType: string | undefined;
    internshipNihii: string | undefined;
    internshipSsin: string | undefined;
    internshipLastName: string | undefined;
    internshipFirstName: string | undefined;
    internshipCdHcParty: string | undefined;
    internshipCbe: string | undefined;
    supervisorNihii: string | undefined;
    supervisorSsin: string | undefined;
    supervisorLastName: string | undefined;
    supervisorFirstName: string | undefined;
    supervisorCdHcParty: string | undefined;
    supervisorCbe: string | undefined;
    error: string | undefined;
    encounterLocationName: string | undefined;
    encounterLocationNihii: string | undefined;
    encounterLocationNorm: number | undefined;
    longDelayJustification: number | undefined;
    correctiveInvoiceId: string | undefined;
    correctedInvoiceId: string | undefined;
    creditNote: boolean | undefined;
    creditNoteRelatedInvoiceId: string | undefined;
    idDocument: IdentityDocumentReader | undefined;
    admissionDate: number | undefined;
    locationNihii: string | undefined;
    locationService: number | undefined;
    cancelReason: string | undefined;
    cancelDate: number | undefined;
    options: {
        [key: string]: string;
    };
    secretForeignKeys: Array<string>;
    cryptedForeignKeys: {
        [key: string]: Array<Delegation>;
    };
    delegations: {
        [key: string]: Array<Delegation>;
    };
    encryptionKeys: {
        [key: string]: Array<Delegation>;
    };
    encryptedSelf: Base64String | undefined;
    securityMetadata: SecurityMetadata | undefined;
    readonly isEncrypted: false;
    constructor(partial: Partial<DecryptedInvoice>);
}
export declare class EncryptedInvoice {
    id: string;
    rev: string | undefined;
    created: number | undefined;
    modified: number | undefined;
    author: string | undefined;
    responsible: string | undefined;
    medicalLocationId: string | undefined;
    tags: Array<CodeStub>;
    codes: Array<CodeStub>;
    endOfLife: number | undefined;
    deletionDate: number | undefined;
    invoiceDate: number | undefined;
    sentDate: number | undefined;
    printedDate: number | undefined;
    invoicingCodes: Array<EncryptedInvoicingCode>;
    receipts: {
        [key: string]: string;
    };
    recipientType: string | undefined;
    recipientId: string | undefined;
    invoiceReference: string | undefined;
    thirdPartyReference: string | undefined;
    thirdPartyPaymentJustification: string | undefined;
    thirdPartyPaymentReason: string | undefined;
    reason: string | undefined;
    invoiceType: InvoiceType | undefined;
    sentMediumType: MediumType | undefined;
    interventionType: InvoiceInterventionType | undefined;
    groupId: string | undefined;
    paymentType: PaymentType | undefined;
    paid: number | undefined;
    payments: Array<Payment> | undefined;
    gnotionNihii: string | undefined;
    gnotionSsin: string | undefined;
    gnotionLastName: string | undefined;
    gnotionFirstName: string | undefined;
    gnotionCdHcParty: string | undefined;
    invoicePeriod: number | undefined;
    careProviderType: string | undefined;
    internshipNihii: string | undefined;
    internshipSsin: string | undefined;
    internshipLastName: string | undefined;
    internshipFirstName: string | undefined;
    internshipCdHcParty: string | undefined;
    internshipCbe: string | undefined;
    supervisorNihii: string | undefined;
    supervisorSsin: string | undefined;
    supervisorLastName: string | undefined;
    supervisorFirstName: string | undefined;
    supervisorCdHcParty: string | undefined;
    supervisorCbe: string | undefined;
    error: string | undefined;
    encounterLocationName: string | undefined;
    encounterLocationNihii: string | undefined;
    encounterLocationNorm: number | undefined;
    longDelayJustification: number | undefined;
    correctiveInvoiceId: string | undefined;
    correctedInvoiceId: string | undefined;
    creditNote: boolean | undefined;
    creditNoteRelatedInvoiceId: string | undefined;
    idDocument: IdentityDocumentReader | undefined;
    admissionDate: number | undefined;
    locationNihii: string | undefined;
    locationService: number | undefined;
    cancelReason: string | undefined;
    cancelDate: number | undefined;
    options: {
        [key: string]: string;
    };
    secretForeignKeys: Array<string>;
    cryptedForeignKeys: {
        [key: string]: Array<Delegation>;
    };
    delegations: {
        [key: string]: Array<Delegation>;
    };
    encryptionKeys: {
        [key: string]: Array<Delegation>;
    };
    encryptedSelf: Base64String | undefined;
    securityMetadata: SecurityMetadata | undefined;
    readonly isEncrypted: true;
    constructor(partial: Partial<EncryptedInvoice>);
}
