export const FAKE_PATIENTS = [
  {
    picture: 'Erin Lindford',
    name: 'Erin Lindford',
    dateOfBirth: '21.12.1989',
    email: 'erin.lindford@gmail.com',
    phoneNumber: '+3289090909',
    diagnosis: 'Paranoid schizophrenia, Major depressive disorder',
    complains: 'Headache, Acne, Breast tenderness, Сramps, Fatigue, Anxiety, Mood swings, Swelling of the body, Irritation, Changes in appetite',
  },
  {
    picture: 'John Doe',
    name: 'John Doe',
    dateOfBirth: '10.05.1975',
    email: 'john.doe@example.com',
    phoneNumber: '+1234567890',
    diagnosis: 'Hypertension, Type 2 Diabetes, Migraine',
    complains: 'High blood pressure, Fatigue, Frequent headaches, Thirst, Blurred vision, Nausea',
  },
  {
    picture: 'Alice Smith',
    name: 'Alice Smith',
    dateOfBirth: '03.09.1993',
    email: 'alice.smith@example.com',
    phoneNumber: '+9876543210',
    diagnosis: 'Asthma, Allergic rhinitis',
    complains: 'Shortness of breath, Coughing, Sneezing, Runny nose, Itchy eyes',
  },
  {
    picture: 'David Johnson',
    name: 'David Johnson',
    dateOfBirth: '15.07.1980',
    email: 'david.johnson@example.com',
    phoneNumber: '+5555555555',
    diagnosis: 'Osteoarthritis, High Cholesterol',
    complains: 'Joint pain, Stiffness, High cholesterol levels',
  },
  {
    picture: 'Emily Brown',
    name: 'Emily Brown',
    dateOfBirth: '28.03.1997',
    email: 'emily.brown@example.com',
    phoneNumber: '+1111111111',
    diagnosis: 'Anxiety disorder, Insomnia',
    complains: 'Trouble sleeping, Excessive worrying, Restlessness',
  },
  {
    picture: 'Michael Wilson',
    name: 'Michael Wilson',
    dateOfBirth: '02.11.1985',
    email: 'michael.wilson@example.com',
    phoneNumber: '+9999999999',
    diagnosis: 'Rheumatoid arthritis, Hypothyroidism',
    complains: 'Joint pain, Fatigue, Weight gain, Hair loss, Muscle weakness',
  },
  {
    picture: 'Sophia Davis',
    name: 'Sophia Davis',
    dateOfBirth: '19.06.1990',
    email: 'sophia.davis@example.com',
    phoneNumber: '+7777777777',
    diagnosis: 'Migraine, Irritable Bowel Syndrome (IBS)',
    complains: 'Frequent headaches, Abdominal pain, Bloating, Diarrhea, Constipation',
  },
  {
    picture: 'William Martinez',
    name: 'William Martinez',
    dateOfBirth: '14.02.1972',
    email: 'william.martinez@example.com',
    phoneNumber: '+2222222222',
    diagnosis: 'Type 1 Diabetes, Hypertension',
    complains: 'High blood sugar, Thirst, Frequent urination, High blood pressure',
  },
  {
    picture: 'Olivia White',
    name: 'Olivia White',
    dateOfBirth: '30.09.1988',
    email: 'olivia.white@example.com',
    phoneNumber: '+8888888888',
    diagnosis: 'Asthma, Allergic dermatitis',
    complains: 'Wheezing, Skin rash, Itchy skin, Redness, Swelling',
  },
  {
    picture: 'Daniel Taylor',
    name: 'Daniel Taylor',
    dateOfBirth: '07.04.1995',
    email: 'daniel.taylor@example.com',
    phoneNumber: '+6666666666',
    diagnosis: 'Depression, Social anxiety disorder',
    complains: 'Low mood, Isolation, Nervousness in social situations, Lack of energy',
  },
]
