export declare class FlowItem {
    id: string | undefined;
    title: string | undefined;
    comment: string | undefined;
    receptionDate: number | undefined;
    processingDate: number | undefined;
    processer: string | undefined;
    cancellationDate: number | undefined;
    canceller: string | undefined;
    cancellationReason: string | undefined;
    cancellationNote: string | undefined;
    status: string | undefined;
    homeVisit: boolean | undefined;
    municipality: string | undefined;
    town: string | undefined;
    zipCode: string | undefined;
    street: string | undefined;
    building: string | undefined;
    buildingNumber: string | undefined;
    doorbellName: string | undefined;
    floor: string | undefined;
    letterBox: string | undefined;
    notesOps: string | undefined;
    notesContact: string | undefined;
    latitude: string | undefined;
    longitude: string | undefined;
    type: string | undefined;
    emergency: boolean | undefined;
    phoneNumber: string | undefined;
    patientId: string | undefined;
    patientLastName: string | undefined;
    patientFirstName: string | undefined;
    description: string | undefined;
    interventionCode: string | undefined;
    constructor(partial: Partial<FlowItem>);
}
