import { CodeStub } from '../base/CodeStub.mjs';
import { Duration } from './Duration.mjs';
import { Medicinalproduct } from './Medicinalproduct.mjs';
import { ParagraphAgreement } from './ParagraphAgreement.mjs';
import { RegimenItem } from './RegimenItem.mjs';
import { Renewal } from './Renewal.mjs';
import { Substanceproduct } from './Substanceproduct.mjs';
import { Suspension } from './Suspension.mjs';
export declare class Medication {
    compoundPrescription: string | undefined;
    substanceProduct: Substanceproduct | undefined;
    medicinalProduct: Medicinalproduct | undefined;
    numberOfPackages: number | undefined;
    batch: string | undefined;
    expirationDate: number | undefined;
    instructionForPatient: string | undefined;
    instructionForReimbursement: string | undefined;
    commentForDelivery: string | undefined;
    drugRoute: string | undefined;
    temporality: string | undefined;
    frequency: CodeStub | undefined;
    reimbursementReason: CodeStub | undefined;
    substitutionAllowed: boolean | undefined;
    beginMoment: number | undefined;
    endMoment: number | undefined;
    deliveryMoment: number | undefined;
    endExecutionMoment: number | undefined;
    duration: Duration | undefined;
    renewal: Renewal | undefined;
    knownUsage: boolean | undefined;
    regimen: Array<RegimenItem> | undefined;
    posology: string | undefined;
    agreements: {
        [key: string]: ParagraphAgreement;
    } | undefined;
    medicationSchemeIdOnSafe: string | undefined;
    medicationSchemeSafeVersion: number | undefined;
    medicationSchemeTimeStampOnSafe: number | undefined;
    medicationSchemeDocumentId: string | undefined;
    safeIdName: string | undefined;
    idOnSafes: string | undefined;
    timestampOnSafe: number | undefined;
    changeValidated: boolean | undefined;
    newSafeMedication: boolean | undefined;
    medicationUse: string | undefined;
    beginCondition: string | undefined;
    endCondition: string | undefined;
    origin: string | undefined;
    medicationChanged: boolean | undefined;
    posologyChanged: boolean | undefined;
    suspension: Array<Suspension> | undefined;
    prescriptionRID: string | undefined;
    status: number | undefined;
    constructor(partial: Partial<Medication>);
}
