import { CodeStub } from '../base/CodeStub.mjs';
import { ICureDocument } from '../base/ICureDocument.mjs';
import { Named } from '../base/Named.mjs';
import { Base64String } from '../specializations/Base64String.mjs';
import { CareTeamMembership, DecryptedCareTeamMembership, EncryptedCareTeamMembership } from './CareTeamMembership.mjs';
import { Encryptable } from './Encryptable.mjs';
export interface PlanOfAction extends Encryptable, ICureDocument<string>, Named {
    prescriberId: string | undefined;
    valueDate: number | undefined;
    openingDate: number | undefined;
    closingDate: number | undefined;
    deadlineDate: number | undefined;
    descr: string | undefined;
    note: string | undefined;
    idOpeningContact: string | undefined;
    idClosingContact: string | undefined;
    status: number;
    documentIds: Array<string>;
    numberOfCares: number | undefined;
    careTeamMemberships: Array<CareTeamMembership | undefined>;
    relevant: boolean;
    readonly isEncrypted: boolean;
}
export declare class DecryptedPlanOfAction {
    id: string;
    created: number | undefined;
    modified: number | undefined;
    author: string | undefined;
    responsible: string | undefined;
    medicalLocationId: string | undefined;
    tags: Array<CodeStub>;
    codes: Array<CodeStub>;
    endOfLife: number | undefined;
    prescriberId: string | undefined;
    valueDate: number | undefined;
    openingDate: number | undefined;
    closingDate: number | undefined;
    deadlineDate: number | undefined;
    name: string | undefined;
    descr: string | undefined;
    note: string | undefined;
    idOpeningContact: string | undefined;
    idClosingContact: string | undefined;
    status: number;
    documentIds: Array<string>;
    numberOfCares: number | undefined;
    careTeamMemberships: Array<DecryptedCareTeamMembership | undefined>;
    relevant: boolean;
    encryptedSelf: Base64String | undefined;
    readonly isEncrypted: false;
    constructor(partial: Partial<DecryptedPlanOfAction>);
}
export declare class EncryptedPlanOfAction {
    id: string;
    created: number | undefined;
    modified: number | undefined;
    author: string | undefined;
    responsible: string | undefined;
    medicalLocationId: string | undefined;
    tags: Array<CodeStub>;
    codes: Array<CodeStub>;
    endOfLife: number | undefined;
    prescriberId: string | undefined;
    valueDate: number | undefined;
    openingDate: number | undefined;
    closingDate: number | undefined;
    deadlineDate: number | undefined;
    name: string | undefined;
    descr: string | undefined;
    note: string | undefined;
    idOpeningContact: string | undefined;
    idClosingContact: string | undefined;
    status: number;
    documentIds: Array<string>;
    numberOfCares: number | undefined;
    careTeamMemberships: Array<EncryptedCareTeamMembership | undefined>;
    relevant: boolean;
    encryptedSelf: Base64String | undefined;
    readonly isEncrypted: true;
    constructor(partial: Partial<EncryptedPlanOfAction>);
}
