steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: [ '-c', 'git fetch --unshallow --tags && git checkout ${BRANCH_NAME} && git submodule init && git submodule update' ]

  - name: 'docker'
    args: [ "build", "--build-arg", "VITE_EXTERNAL_SERVICES_SPEC_ID=${_VITE_EXTERNAL_SERVICES_SPEC_ID}", "--build-arg", "VITE_EMAIL_AUTHENTICATION_PROCESS_ID=${_VITE_EMAIL_AUTHENTICATION_PROCESS_ID}", "--build-arg", "VITE_PARENT_ORGANISATION_ID=${_VITE_PARENT_ORGANISATION_ID}", "-t", "docker.taktik.be/icure-ehr-lite-practitioner-elements-app", "." ]

  - name: 'docker.taktik.be/icure-ehr-lite-practitioner-elements-app'
    entrypoint: sh
    args: [ '-c', 'cp -af /app/build /workspace' ]

  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ "-m", "rsync", "-r", "-c", "-d", "./build", "${_DEPLOY}" ]

timeout: 1800s
